authors=[Rutger Pijnenburg](https\://myDomain.com)
categories=Fabrication
maxRevision=0
minRevision=0
name=Direct Embroidery Control
paragraph=
prettyVersion=1.0.0
sentence=This library can be used to communicate directly to a Brother embroidery machine
url=https\://myDomain.com/myLibrary
version=1
